const CloudHat = new Enum({
    "Unknown":'Unknown',
    "Altostratus":'altostratus',
    "Cirrus":'Cirrus',
    "Cirrocumulus":'cirrocumulus',
    "Clear":'Clear 01',
    "Cloudy":'Cloudy 01',
    "Contrails":'Contrails',
    "Horizon":'Horizon',
    "HorizonBand1":'horizonband1',
    "HorizonBand2":'horizonband2',
    "HorizonBand3":'horizonband3',
    "Horsey":'horsey',
    "Nimbus":'Nimbus',
    "Puffs":'Puffs',
    "Rain":'RAIN',
    "Snowy":'Snowy 01',
    "Stormy":'Stormy 01',
    "Stratoscumulus":'stratoscumulus',
    "Stripey":'Stripey',
    "Shower": 'shower',
    "Wispy":'Wispy',
})